package:
    name:           unified-omnipay-webmoney
    namespace:      UnifiedOmnipay\WebMoney
    title:          WebMoney driver for the Unified Omnipay PHP payment processing library
    type:           library
    keywords:       php, webmoney, omnipay, unifiedomnipay, merchant, payment
    description:    |
        [WebMoney](http://webmoney.ru/) driver for the [Unified](https://github.com/hiqdev/unified-omnipay)
        [Omnipay](http://omnipay.thephpleague.com/) PHP payment processing library.

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
