package:
    name:           omnipay-webmoney
    namespace:      Omnipay\WebMoney
    title:          WebMoney driver for the Omnipay PHP payment processing library
    type:           library
    keywords:       php, omnipay, webmoney, merchant, payment
    description:    |
        [WebMoney](http://webmoney.ru/) driver for the [Omnipay](http://omnipay.thephpleague.com/) PHP payment processing library.

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
