package:
    name:           php-merchant-webmoney
    namespace:      hiqdev\php\merchant\webmoney
    title:          WebMoney plugin for PHP merchant library
    type:           library
    keywords:       php, webmoney, merchant
    description:    |
        [WebMoney](http://webmoney.ru/) plugin for [PHP merchant library](https://github.com/hiqdev/php-merchant).

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
